version: "3"
services:
  foodbag:
    build: '.'
    depends_on:
      - foodbagdb
    ports:
      - 8080:8080
      - 5005:5005
      - 35729:35729
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://foodbagdb:3306/foods&characterEncoding=utf8&useSSL=false
  foodbagdb:
    image: mariadb
    build: './mariadb'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: ["mysqld",
        "--skip-name-resolve",
        "--skip-ssl",
        "--character_set_server=utf8"]
